version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    depends_on:
      - postgres
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://postgres:5432/demo
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
    ports:
      - "8080:8080"

volumes:
  pgdata:
